"""
Email service module.

This module handles email verification functionality using FastAPI-Mail
and itsdangerous serializer. It provides token generation, validation,
and sending verification emails.

Environment Variables:
    MAIL_USERNAME (str): SMTP username.
    MAIL_PASSWORD (str): SMTP password.
    MAIL_FROM (str): Sender email address.
    MAIL_PORT (int): SMTP port.
    MAIL_SERVER (str): SMTP server host.
    SECRET_KEY (str): Secret key used for token generation.

Security:
    - Email tokens are signed using URLSafeTimedSerializer.
    - Tokens expire after 1 hour.
"""

from fastapi_mail import FastMail, MessageSchema, ConnectionConfig
from itsdangerous import URLSafeTimedSerializer
from os import getenv
from dotenv import load_dotenv

import smtplib
from email.mime.text import MIMEText
import os

load_dotenv()

conf = ConnectionConfig(
    MAIL_USERNAME=getenv("MAIL_USERNAME"),
    MAIL_PASSWORD=getenv("MAIL_PASSWORD"),
    MAIL_FROM=getenv("MAIL_FROM"),
    MAIL_PORT=int(getenv("MAIL_PORT")),
    MAIL_SERVER=getenv("MAIL_SERVER"),
    MAIL_STARTTLS=True,
    MAIL_SSL_TLS=False,
    USE_CREDENTIALS=True,
)

serializer = URLSafeTimedSerializer(getenv("SECRET_KEY"))


def create_email_token(email: str) -> str:
    """
    Generate a secure email verification token.

    Args:
        email (str): User email address.

    Returns:
        str: Signed token containing the email.
    """
    return serializer.dumps(email, salt="email-confirm")


def confirm_email_token(token: str) -> str:
    """
    Validate and decode an email verification token.

    Args:
        token (str): Verification token.

    Returns:
        str: Email extracted from token.

    Raises:
        BadSignature or SignatureExpired: If token is invalid or expired.
    """
    return serializer.loads(
        token,
        salt="email-confirm",
        max_age=3600
    )


async def send_verification_email(email: str, host: str, token: str):
    """
    Send email verification message to the user.

    Args:
        email (str): Recipient email address.
        host (str): Base URL of the application.
        token (str): Email verification token.

    Returns:
        None
    """
    verify_url = f"{host}auth/verify?token={token}"

    message = MessageSchema(
        subject="Verify your email",
        recipients=[email],
        body=f"""
        <h2>Email Verification</h2>
        <p>Click the button below to verify your email:</p>
        <a href="{verify_url}"
           style="display:inline-block;padding:10px 20px;
           background:#4CAF50;color:white;text-decoration:none;">
           VERIFY EMAIL
        </a>
        <p>This link will expire in 1 hour.</p>
        """,
        subtype="html"
    )

    fm = FastMail(conf)
    await fm.send_message(message)

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

def send_reset_email(email: str, token: str):
    """
    Send password reset email to the user.

    Args:
        email (str): Recipient email address.
        token (str): Password reset token generated by the system.

    Returns:
        None

    Raises:
        smtplib.SMTPException: If email sending fails.
    """
    reset_link = f"http://localhost:8000/reset-password?token={token}"
    msg = MIMEText(f"Click to reset password: {reset_link}")
    msg["Subject"] = "Password Reset"
    msg["From"] = SMTP_USER
    msg["To"] = email
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.send_message(msg)